[package]
name = "simple-cd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
fs_extra = "1.3.0"
rocket = {version = "=0.5.0-rc.3", features = ["json"]}
run_script = "0.10.1"
